/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityStatisticsResponseDto {
    #[serde(rename = "comments")]
    pub comments: i32,
}

impl ActivityStatisticsResponseDto {
    pub fn new(comments: i32) -> ActivityStatisticsResponseDto {
        ActivityStatisticsResponseDto {
            comments,
        }
    }
}

