/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddUsersDto {
    #[serde(rename = "albumUsers")]
    pub album_users: Vec<models::AlbumUserAddDto>,
}

impl AddUsersDto {
    pub fn new(album_users: Vec<models::AlbumUserAddDto>) -> AddUsersDto {
        AddUsersDto {
            album_users,
        }
    }
}

