/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumUserResponseDto {
    #[serde(rename = "role")]
    pub role: models::AlbumUserRole,
    #[serde(rename = "user")]
    pub user: Box<models::UserResponseDto>,
}

impl AlbumUserResponseDto {
    pub fn new(role: models::AlbumUserRole, user: models::UserResponseDto) -> AlbumUserResponseDto {
        AlbumUserResponseDto {
            role,
            user: Box::new(user),
        }
    }
}

