/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyCreateResponseDto {
    #[serde(rename = "apiKey")]
    pub api_key: Box<models::ApiKeyResponseDto>,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl ApiKeyCreateResponseDto {
    pub fn new(api_key: models::ApiKeyResponseDto, secret: String) -> ApiKeyCreateResponseDto {
        ApiKeyCreateResponseDto {
            api_key: Box::new(api_key),
            secret,
        }
    }
}

