/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetBulkUploadCheckItem {
    /// base64 or hex encoded sha1 hash
    #[serde(rename = "checksum")]
    pub checksum: String,
    #[serde(rename = "id")]
    pub id: String,
}

impl AssetBulkUploadCheckItem {
    pub fn new(checksum: String, id: String) -> AssetBulkUploadCheckItem {
        AssetBulkUploadCheckItem {
            checksum,
            id,
        }
    }
}

