/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetMediaStatus {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "replaced")]
    Replaced,
    #[serde(rename = "duplicate")]
    Duplicate,

}

impl std::fmt::Display for AssetMediaStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "created"),
            Self::Replaced => write!(f, "replaced"),
            Self::Duplicate => write!(f, "duplicate"),
        }
    }
}

impl Default for AssetMediaStatus {
    fn default() -> AssetMediaStatus {
        Self::Created
    }
}

