/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetFullSyncDto {
    #[serde(rename = "lastCreationDate", skip_serializing_if = "Option::is_none")]
    pub last_creation_date: Option<String>,
    #[serde(rename = "lastId", skip_serializing_if = "Option::is_none")]
    pub last_id: Option<uuid::Uuid>,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "updatedUntil")]
    pub updated_until: String,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
}

impl AssetFullSyncDto {
    pub fn new(limit: i32, updated_until: String) -> AssetFullSyncDto {
        AssetFullSyncDto {
            last_creation_date: None,
            last_id: None,
            limit,
            updated_until,
            user_id: None,
        }
    }
}

