/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetIdsResponseDto {
    #[serde(rename = "assetId")]
    pub asset_id: String,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Error>,
    #[serde(rename = "success")]
    pub success: bool,
}

impl AssetIdsResponseDto {
    pub fn new(asset_id: String, success: bool) -> AssetIdsResponseDto {
        AssetIdsResponseDto {
            asset_id,
            error: None,
            success,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "no_permission")]
    NoPermission,
    #[serde(rename = "not_found")]
    NotFound,
}

impl Default for Error {
    fn default() -> Error {
        Self::Duplicate
    }
}

