/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetFaceUpdateDto {
    #[serde(rename = "data")]
    pub data: Vec<models::AssetFaceUpdateItem>,
}

impl AssetFaceUpdateDto {
    pub fn new(data: Vec<models::AssetFaceUpdateItem>) -> AssetFaceUpdateDto {
        AssetFaceUpdateDto {
            data,
        }
    }
}

