/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckExistingAssetsResponseDto {
    #[serde(rename = "existingIds")]
    pub existing_ids: Vec<String>,
}

impl CheckExistingAssetsResponseDto {
    pub fn new(existing_ids: Vec<String>) -> CheckExistingAssetsResponseDto {
        CheckExistingAssetsResponseDto {
            existing_ids,
        }
    }
}

