/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClipMode {
    #[serde(rename = "vision")]
    Vision,
    #[serde(rename = "text")]
    Text,

}

impl std::fmt::Display for ClipMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Vision => write!(f, "vision"),
            Self::Text => write!(f, "text"),
        }
    }
}

impl Default for ClipMode {
    fn default() -> ClipMode {
        Self::Vision
    }
}

