/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CqMode {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "cqp")]
    Cqp,
    #[serde(rename = "icq")]
    Icq,

}

impl std::fmt::Display for CqMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Auto => write!(f, "auto"),
            Self::Cqp => write!(f, "cqp"),
            Self::Icq => write!(f, "icq"),
        }
    }
}

impl Default for CqMode {
    fn default() -> CqMode {
        Self::Auto
    }
}

