/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DuplicateDetectionConfig {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "maxDistance")]
    pub max_distance: f32,
}

impl DuplicateDetectionConfig {
    pub fn new(enabled: bool, max_distance: f32) -> DuplicateDetectionConfig {
        DuplicateDetectionConfig {
            enabled,
            max_distance,
        }
    }
}

