/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailNotificationsUpdate {
    #[serde(rename = "albumInvite", skip_serializing_if = "Option::is_none")]
    pub album_invite: Option<bool>,
    #[serde(rename = "albumUpdate", skip_serializing_if = "Option::is_none")]
    pub album_update: Option<bool>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl EmailNotificationsUpdate {
    pub fn new() -> EmailNotificationsUpdate {
        EmailNotificationsUpdate {
            album_invite: None,
            album_update: None,
            enabled: None,
        }
    }
}

