/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailNotificationsResponse {
    #[serde(rename = "albumInvite")]
    pub album_invite: bool,
    #[serde(rename = "albumUpdate")]
    pub album_update: bool,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl EmailNotificationsResponse {
    pub fn new(album_invite: bool, album_update: bool, enabled: bool) -> EmailNotificationsResponse {
        EmailNotificationsResponse {
            album_invite,
            album_update,
            enabled,
        }
    }
}

