/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExifResponseDto {
    #[serde(rename = "city", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city: Option<Option<String>>,
    #[serde(rename = "country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country: Option<Option<String>>,
    #[serde(rename = "dateTimeOriginal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_time_original: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "exifImageHeight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exif_image_height: Option<Option<f64>>,
    #[serde(rename = "exifImageWidth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exif_image_width: Option<Option<f64>>,
    #[serde(rename = "exposureTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exposure_time: Option<Option<String>>,
    #[serde(rename = "fNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub f_number: Option<Option<f64>>,
    #[serde(rename = "fileSizeInByte", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_size_in_byte: Option<Option<i64>>,
    #[serde(rename = "focalLength", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub focal_length: Option<Option<f64>>,
    #[serde(rename = "iso", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iso: Option<Option<f64>>,
    #[serde(rename = "latitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Option<f64>>,
    #[serde(rename = "lensModel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lens_model: Option<Option<String>>,
    #[serde(rename = "longitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Option<f64>>,
    #[serde(rename = "make", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub make: Option<Option<String>>,
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    #[serde(rename = "modifyDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub modify_date: Option<Option<String>>,
    #[serde(rename = "orientation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub orientation: Option<Option<String>>,
    #[serde(rename = "projectionType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub projection_type: Option<Option<String>>,
    #[serde(rename = "state", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state: Option<Option<String>>,
    #[serde(rename = "timeZone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<Option<String>>,
}

impl ExifResponseDto {
    pub fn new() -> ExifResponseDto {
        ExifResponseDto {
            city: None,
            country: None,
            date_time_original: None,
            description: None,
            exif_image_height: None,
            exif_image_width: None,
            exposure_time: None,
            f_number: None,
            file_size_in_byte: None,
            focal_length: None,
            iso: None,
            latitude: None,
            lens_model: None,
            longitude: None,
            make: None,
            model: None,
            modify_date: None,
            orientation: None,
            projection_type: None,
            state: None,
            time_zone: None,
        }
    }
}

