/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileChecksumResponseDto {
    #[serde(rename = "checksum")]
    pub checksum: String,
    #[serde(rename = "filename")]
    pub filename: String,
}

impl FileChecksumResponseDto {
    pub fn new(checksum: String, filename: String) -> FileChecksumResponseDto {
        FileChecksumResponseDto {
            checksum,
            filename,
        }
    }
}

