/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileChecksumDto {
    #[serde(rename = "filenames")]
    pub filenames: Vec<String>,
}

impl FileChecksumDto {
    pub fn new(filenames: Vec<String>) -> FileChecksumDto {
        FileChecksumDto {
            filenames,
        }
    }
}

