/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobCommandDto {
    #[serde(rename = "command")]
    pub command: models::JobCommand,
    #[serde(rename = "force")]
    pub force: bool,
}

impl JobCommandDto {
    pub fn new(command: models::JobCommand, force: bool) -> JobCommandDto {
        JobCommandDto {
            command,
            force,
        }
    }
}

