/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobCountsDto {
    #[serde(rename = "active")]
    pub active: i32,
    #[serde(rename = "completed")]
    pub completed: i32,
    #[serde(rename = "delayed")]
    pub delayed: i32,
    #[serde(rename = "failed")]
    pub failed: i32,
    #[serde(rename = "paused")]
    pub paused: i32,
    #[serde(rename = "waiting")]
    pub waiting: i32,
}

impl JobCountsDto {
    pub fn new(active: i32, completed: i32, delayed: i32, failed: i32, paused: i32, waiting: i32) -> JobCountsDto {
        JobCountsDto {
            active,
            completed,
            delayed,
            failed,
            paused,
            waiting,
        }
    }
}

