/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthConfigDto {
    #[serde(rename = "redirectUri")]
    pub redirect_uri: String,
}

impl OAuthConfigDto {
    pub fn new(redirect_uri: String) -> OAuthConfigDto {
        OAuthConfigDto {
            redirect_uri,
        }
    }
}

