/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerResponseDto {
    #[serde(rename = "avatarColor")]
    pub avatar_color: models::UserAvatarColor,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "inTimeline", skip_serializing_if = "Option::is_none")]
    pub in_timeline: Option<bool>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "profileImagePath")]
    pub profile_image_path: String,
}

impl PartnerResponseDto {
    pub fn new(avatar_color: models::UserAvatarColor, email: String, id: String, name: String, profile_image_path: String) -> PartnerResponseDto {
        PartnerResponseDto {
            avatar_color,
            email,
            id,
            in_timeline: None,
            name,
            profile_image_path,
        }
    }
}

