/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueStatusDto {
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "isPaused")]
    pub is_paused: bool,
}

impl QueueStatusDto {
    pub fn new(is_active: bool, is_paused: bool) -> QueueStatusDto {
        QueueStatusDto {
            is_active,
            is_paused,
        }
    }
}

