/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReactionLevel {
    #[serde(rename = "album")]
    Album,
    #[serde(rename = "asset")]
    Asset,

}

impl std::fmt::Display for ReactionLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Album => write!(f, "album"),
            Self::Asset => write!(f, "asset"),
        }
    }
}

impl Default for ReactionLevel {
    fn default() -> ReactionLevel {
        Self::Album
    }
}

