/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchExploreResponseDto {
    #[serde(rename = "fieldName")]
    pub field_name: String,
    #[serde(rename = "items")]
    pub items: Vec<models::SearchExploreItem>,
}

impl SearchExploreResponseDto {
    pub fn new(field_name: String, items: Vec<models::SearchExploreItem>) -> SearchExploreResponseDto {
        SearchExploreResponseDto {
            field_name,
            items,
        }
    }
}

