/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchSuggestionType {
    #[serde(rename = "country")]
    Country,
    #[serde(rename = "state")]
    State,
    #[serde(rename = "city")]
    City,
    #[serde(rename = "camera-make")]
    CameraMake,
    #[serde(rename = "camera-model")]
    CameraModel,

}

impl std::fmt::Display for SearchSuggestionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Country => write!(f, "country"),
            Self::State => write!(f, "state"),
            Self::City => write!(f, "city"),
            Self::CameraMake => write!(f, "camera-make"),
            Self::CameraModel => write!(f, "camera-model"),
        }
    }
}

impl Default for SearchSuggestionType {
    fn default() -> SearchSuggestionType {
        Self::Country
    }
}

