/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchAlbumResponseDto {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "facets")]
    pub facets: Vec<models::SearchFacetResponseDto>,
    #[serde(rename = "items")]
    pub items: Vec<models::AlbumResponseDto>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl SearchAlbumResponseDto {
    pub fn new(count: i32, facets: Vec<models::SearchFacetResponseDto>, items: Vec<models::AlbumResponseDto>, total: i32) -> SearchAlbumResponseDto {
        SearchAlbumResponseDto {
            count,
            facets,
            items,
            total,
        }
    }
}

