/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerStatsResponseDto {
    #[serde(rename = "photos")]
    pub photos: i32,
    #[serde(rename = "usage")]
    pub usage: i64,
    #[serde(rename = "usageByUser")]
    pub usage_by_user: Vec<models::UsageByUserDto>,
    #[serde(rename = "videos")]
    pub videos: i32,
}

impl ServerStatsResponseDto {
    pub fn new(photos: i32, usage: i64, usage_by_user: Vec<models::UsageByUserDto>, videos: i32) -> ServerStatsResponseDto {
        ServerStatsResponseDto {
            photos,
            usage,
            usage_by_user,
            videos,
        }
    }
}

