/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerMediaTypesResponseDto {
    #[serde(rename = "image")]
    pub image: Vec<String>,
    #[serde(rename = "sidecar")]
    pub sidecar: Vec<String>,
    #[serde(rename = "video")]
    pub video: Vec<String>,
}

impl ServerMediaTypesResponseDto {
    pub fn new(image: Vec<String>, sidecar: Vec<String>, video: Vec<String>) -> ServerMediaTypesResponseDto {
        ServerMediaTypesResponseDto {
            image,
            sidecar,
            video,
        }
    }
}

