/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerVersionResponseDto {
    #[serde(rename = "major")]
    pub major: i32,
    #[serde(rename = "minor")]
    pub minor: i32,
    #[serde(rename = "patch")]
    pub patch: i32,
}

impl ServerVersionResponseDto {
    pub fn new(major: i32, minor: i32, patch: i32) -> ServerVersionResponseDto {
        ServerVersionResponseDto {
            major,
            minor,
            patch,
        }
    }
}

