/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerFeaturesDto {
    #[serde(rename = "configFile")]
    pub config_file: bool,
    #[serde(rename = "duplicateDetection")]
    pub duplicate_detection: bool,
    #[serde(rename = "email")]
    pub email: bool,
    #[serde(rename = "facialRecognition")]
    pub facial_recognition: bool,
    #[serde(rename = "map")]
    pub map: bool,
    #[serde(rename = "oauth")]
    pub oauth: bool,
    #[serde(rename = "oauthAutoLaunch")]
    pub oauth_auto_launch: bool,
    #[serde(rename = "passwordLogin")]
    pub password_login: bool,
    #[serde(rename = "reverseGeocoding")]
    pub reverse_geocoding: bool,
    #[serde(rename = "search")]
    pub search: bool,
    #[serde(rename = "sidecar")]
    pub sidecar: bool,
    #[serde(rename = "smartSearch")]
    pub smart_search: bool,
    #[serde(rename = "trash")]
    pub trash: bool,
}

impl ServerFeaturesDto {
    pub fn new(config_file: bool, duplicate_detection: bool, email: bool, facial_recognition: bool, map: bool, oauth: bool, oauth_auto_launch: bool, password_login: bool, reverse_geocoding: bool, search: bool, sidecar: bool, smart_search: bool, trash: bool) -> ServerFeaturesDto {
        ServerFeaturesDto {
            config_file,
            duplicate_detection,
            email,
            facial_recognition,
            map,
            oauth,
            oauth_auto_launch,
            password_login,
            reverse_geocoding,
            search,
            sidecar,
            smart_search,
            trash,
        }
    }
}

