/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SharedLinkType {
    #[serde(rename = "ALBUM")]
    Album,
    #[serde(rename = "INDIVIDUAL")]
    Individual,

}

impl std::fmt::Display for SharedLinkType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Album => write!(f, "ALBUM"),
            Self::Individual => write!(f, "INDIVIDUAL"),
        }
    }
}

impl Default for SharedLinkType {
    fn default() -> SharedLinkType {
        Self::Album
    }
}

