/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigJobDto {
    #[serde(rename = "backgroundTask")]
    pub background_task: Box<models::JobSettingsDto>,
    #[serde(rename = "faceDetection")]
    pub face_detection: Box<models::JobSettingsDto>,
    #[serde(rename = "library")]
    pub library: Box<models::JobSettingsDto>,
    #[serde(rename = "metadataExtraction")]
    pub metadata_extraction: Box<models::JobSettingsDto>,
    #[serde(rename = "migration")]
    pub migration: Box<models::JobSettingsDto>,
    #[serde(rename = "notifications")]
    pub notifications: Box<models::JobSettingsDto>,
    #[serde(rename = "search")]
    pub search: Box<models::JobSettingsDto>,
    #[serde(rename = "sidecar")]
    pub sidecar: Box<models::JobSettingsDto>,
    #[serde(rename = "smartSearch")]
    pub smart_search: Box<models::JobSettingsDto>,
    #[serde(rename = "thumbnailGeneration")]
    pub thumbnail_generation: Box<models::JobSettingsDto>,
    #[serde(rename = "videoConversion")]
    pub video_conversion: Box<models::JobSettingsDto>,
}

impl SystemConfigJobDto {
    pub fn new(background_task: models::JobSettingsDto, face_detection: models::JobSettingsDto, library: models::JobSettingsDto, metadata_extraction: models::JobSettingsDto, migration: models::JobSettingsDto, notifications: models::JobSettingsDto, search: models::JobSettingsDto, sidecar: models::JobSettingsDto, smart_search: models::JobSettingsDto, thumbnail_generation: models::JobSettingsDto, video_conversion: models::JobSettingsDto) -> SystemConfigJobDto {
        SystemConfigJobDto {
            background_task: Box::new(background_task),
            face_detection: Box::new(face_detection),
            library: Box::new(library),
            metadata_extraction: Box::new(metadata_extraction),
            migration: Box::new(migration),
            notifications: Box::new(notifications),
            search: Box::new(search),
            sidecar: Box::new(sidecar),
            smart_search: Box::new(smart_search),
            thumbnail_generation: Box::new(thumbnail_generation),
            video_conversion: Box::new(video_conversion),
        }
    }
}

