/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigPasswordLoginDto {
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl SystemConfigPasswordLoginDto {
    pub fn new(enabled: bool) -> SystemConfigPasswordLoginDto {
        SystemConfigPasswordLoginDto {
            enabled,
        }
    }
}

