/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigThemeDto {
    #[serde(rename = "customCss")]
    pub custom_css: String,
}

impl SystemConfigThemeDto {
    pub fn new(custom_css: String) -> SystemConfigThemeDto {
        SystemConfigThemeDto {
            custom_css,
        }
    }
}

