/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigLoggingDto {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "level")]
    pub level: models::LogLevel,
}

impl SystemConfigLoggingDto {
    pub fn new(enabled: bool, level: models::LogLevel) -> SystemConfigLoggingDto {
        SystemConfigLoggingDto {
            enabled,
            level,
        }
    }
}

