/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagTypeEnum {
    #[serde(rename = "OBJECT")]
    Object,
    #[serde(rename = "FACE")]
    Face,
    #[serde(rename = "CUSTOM")]
    Custom,

}

impl std::fmt::Display for TagTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Object => write!(f, "OBJECT"),
            Self::Face => write!(f, "FACE"),
            Self::Custom => write!(f, "CUSTOM"),
        }
    }
}

impl Default for TagTypeEnum {
    fn default() -> TagTypeEnum {
        Self::Object
    }
}

