/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: models::TagTypeEnum,
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl TagResponseDto {
    pub fn new(id: String, name: String, r#type: models::TagTypeEnum, user_id: String) -> TagResponseDto {
        TagResponseDto {
            id,
            name,
            r#type,
            user_id,
        }
    }
}

