/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeBucketSize {
    #[serde(rename = "DAY")]
    Day,
    #[serde(rename = "MONTH")]
    Month,

}

impl std::fmt::Display for TimeBucketSize {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Day => write!(f, "DAY"),
            Self::Month => write!(f, "MONTH"),
        }
    }
}

impl Default for TimeBucketSize {
    fn default() -> TimeBucketSize {
        Self::Day
    }
}

