/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeBucketResponseDto {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "timeBucket")]
    pub time_bucket: String,
}

impl TimeBucketResponseDto {
    pub fn new(count: i32, time_bucket: String) -> TimeBucketResponseDto {
        TimeBucketResponseDto {
            count,
            time_bucket,
        }
    }
}

