/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.105.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPreferencesResponseDto {
    #[serde(rename = "avatar")]
    pub avatar: Box<models::AvatarResponse>,
    #[serde(rename = "emailNotifications")]
    pub email_notifications: Box<models::EmailNotificationsResponse>,
    #[serde(rename = "memories")]
    pub memories: Box<models::MemoryResponse>,
}

impl UserPreferencesResponseDto {
    pub fn new(avatar: models::AvatarResponse, email_notifications: models::EmailNotificationsResponse, memories: models::MemoryResponse) -> UserPreferencesResponseDto {
        UserPreferencesResponseDto {
            avatar: Box::new(avatar),
            email_notifications: Box::new(email_notifications),
            memories: Box::new(memories),
        }
    }
}

